# =============================================================================
# Arquivo: docker-compose.yaml
# Versão: v1.0.0
# Objetivo: Orquestração (Coolify) — INALTERADO
# Funções/métodos:
# - Serviço svc-face-recon-db
# =============================================================================

# docker-compose.yaml — Coolify (produção)
# Evita ${...} dentro de strings complexas (como URLs).
# Defina DATABASE_URL completa nas variáveis de ambiente do Coolify.

# docker-compose.yaml — usado pelo Coolify (mesmo conteúdo do docker-compose.coolify.yaml)
name: svc-face-recon-coolify

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: svc-face-recon-db
    env_file:
      - .env.coolify
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./_data/pg:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 40
      start_period: 90s
    restart: unless-stopped
    networks: [monitoring]

  db-init:
    image: postgres:16-alpine
    container_name: svc-face-recon-db-init
    env_file:
      - .env.coolify
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: |
      set -e
      export PGPASSWORD="${POSTGRES_PASSWORD}"
      psql -v ON_ERROR_STOP=1 -h db -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" <<'SQL'
      CREATE EXTENSION IF NOT EXISTS vector;

      CREATE TABLE IF NOT EXISTS member_faces (
        member_id text PRIMARY KEY,
        embedding vector(512) NOT NULL
      );

      CREATE INDEX IF NOT EXISTS member_faces_hnsw
      ON member_faces USING hnsw (embedding vector_l2_ops)
      WITH (m = 16, ef_construction = 200);
      SQL
    restart: "no"
    networks: [monitoring]

  redis:
    image: redis:7-alpine
    container_name: svc-face-recon-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./_data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 5s
    restart: unless-stopped
    networks: [monitoring]

  svc-face-recon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svc-face-recon
    env_file:
      - .env.coolify
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      HOST: ${HOST}
      PORT: ${PORT}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ./.cache/insightface:/root/.insightface
    restart: unless-stopped
    networks: [monitoring]

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    volumes:
      - ./observabilidade/prometheus:/etc/prometheus:ro
      - ./observabilidade/prometheus/data:/prometheus
    restart: unless-stopped
    networks: [monitoring]

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    env_file:
      - .env.coolify
    volumes:
      - ./observabilidade/grafana/data:/var/lib/grafana
      - ./observabilidade/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
    networks: [monitoring]

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node-exporter
    restart: unless-stopped
    networks: [monitoring]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks: [monitoring]

  datadog:
    image: datadog/agent:7.52.0
    container_name: datadog
    env_file:
      - .env.coolify
    environment:
      DD_SITE: ${DD_SITE}
      DD_LOGS_ENABLED: ${DD_LOGS_ENABLED}
      DD_APM_ENABLED: ${DD_APM_ENABLED}
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: ${DD_DOGSTATSD_NON_LOCAL_TRAFFIC}
      DD_CONTAINER_COLLECT_ALL: ${DD_CONTAINER_COLLECT_ALL}
      DD_PROCESS_AGENT_ENABLED: ${DD_PROCESS_AGENT_ENABLED}
      DD_API_KEY: ${DD_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    restart: unless-stopped
    networks: [monitoring]

networks:
  monitoring:
    driver: bridge
