global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: svc-face-recon
    metrics_path: /metrics
    static_configs:
      - targets: ["svc-face-recon:8000"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
